### ISSUE TITLE
⌘-sortcuts not working on Linux (probably Win too)

### ISSUE THREAD

**Issue by 1ace** [slate/slate#77]
Maybe you should bind on `ctrl`? You can switch on `process.platform` if you want.
Also, [`k`](https://www.npmjs.org/package/k) seem [dead](https://github.com/SheetJS/k) (or did it move?)

**Comment by cjb** [comment]
Dup of #71.  They're not actually implemented yet.

**Comment by 1ace** [comment]
Didn't see it, sorry for the noise

**Comment by MCB-PRO-27** [comment]
You fag Linux users don't know unix!!!! It's like comparing winxp to Ubuntu they both blow!!!

**Comment by frdmn** [comment]
@MCB-PRO-27 you mad bro?

**Comment by notslang** [comment]
Ok, there are a couple points that I want make in regards to your comment, @MCB-PRO-27:
- Linux was developed as an alternative to UNIX, and shares a lot of the same standards. So Linux users understand how to work on a UNIX-like system. Similarly, OS X is UNIX-like, but that has nothing to do with the keyboard shortcuts... UNIX-like refers to much more basic OS utilities & organization.
- I understand that you're new to GitHub, but we try to maintain a relatively high level of professionalism here... Especially because all open-source repos are completely public (including the issue tracker) and you will quickly gain a reputation within the community. Whether that is a positive rep or a negative one is up to you.

**Comment by tj** [comment]
'k' is yields/k
